# Generated by Django 4.0.5 on 2024-09-30 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Circuit ID')),
                ('ref', models.CharField(max_length=100, verbose_name='Circuit Ref')),
                ('name', models.CharField(max_length=100, verbose_name='Circuit Name')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country_flag', models.ImageField(blank=True, default='', upload_to='country/flag')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('altitude', models.IntegerField(blank=True, verbose_name='Altitude')),
                ('url', models.CharField(max_length=100, verbose_name='Circuit Wiki Url')),
            ],
            options={
                'verbose_name_plural': 'Circuits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Constructor ID')),
                ('ref', models.CharField(max_length=100, verbose_name='REF name')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nationality')),
                ('url', models.CharField(max_length=250, verbose_name='Constructor Wiki Url')),
            ],
            options={
                'verbose_name_plural': 'Constructors',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Driver ID')),
                ('Ref', models.CharField(blank=True, max_length=65, null=True)),
                ('number', models.IntegerField(verbose_name='Number driver')),
                ('code', models.CharField(max_length=3, verbose_name='Code Driver')),
                ('fname', models.CharField(max_length=65, verbose_name='First Name')),
                ('lname', models.CharField(max_length=65, verbose_name='Last Name')),
                ('dob', models.DateField(verbose_name='Date of Birthday')),
                ('nationality', models.CharField(max_length=65, verbose_name='Nationality')),
                ('url', models.CharField(max_length=250, verbose_name='Url Driver')),
            ],
            options={
                'verbose_name_plural': 'Drivers',
                'ordering': ['fname'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Race ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('round', models.IntegerField(verbose_name='Round')),
                ('name', models.CharField(max_length=100, verbose_name='GP Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(null=True, verbose_name='Time')),
                ('url', models.CharField(max_length=250, verbose_name='Race Url')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.circuit', verbose_name='Circuit ID')),
            ],
            options={
                'verbose_name_plural': 'Races',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Result ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Number driver')),
                ('grid', models.IntegerField(verbose_name='Starting Grid Position')),
                ('position', models.IntegerField(null=True, verbose_name='Final Position')),
                ('position_text', models.CharField(max_length=65, verbose_name='Position txt')),
                ('position_order', models.IntegerField(blank=True, null=True, verbose_name='Position order')),
                ('points', models.FloatField(verbose_name='Points')),
                ('laps', models.IntegerField(verbose_name='Laps')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.constructor', verbose_name='Constructor ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.driver', verbose_name='Driver ID')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.race', verbose_name='Race ID')),
            ],
            options={
                'verbose_name_plural': 'Results',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='year')),
                ('url', models.CharField(max_length=250, verbose_name='Season Url')),
            ],
            options={
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.CreateModel(
            name='SprintResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Sprint Result ID')),
                ('number', models.IntegerField(verbose_name='Number driver')),
                ('grid', models.IntegerField(verbose_name='Sprint Starting Grid Position')),
                ('position', models.IntegerField(null=True, verbose_name='Sprint Final Position')),
                ('position_text', models.CharField(max_length=65, verbose_name='Sprint Position txt')),
                ('position_order', models.IntegerField(verbose_name='Sprint Position order')),
                ('points', models.FloatField(null=True, verbose_name='Sprint Points')),
                ('laps', models.IntegerField(verbose_name='Sprint Laps')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.constructor', verbose_name='Constructor ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.driver', verbose_name='Driver ID')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.race', verbose_name='Sprint Race ID')),
            ],
            options={
                'verbose_name_plural': 'Sprint results',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='status_id')),
                ('name', models.CharField(max_length=65, verbose_name='status name')),
            ],
            options={
                'verbose_name_plural': 'status',
            },
        ),
        migrations.CreateModel(
            name='SprintResultTime',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Time in milliseconds ID')),
                ('milliseconds', models.IntegerField(blank=True, null=True, verbose_name='Time in Milliseconds')),
                ('sprint_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.sprintresult', verbose_name='Sprint Result ID')),
            ],
            options={
                'verbose_name_plural': 'Milliseconds',
            },
        ),
        migrations.AddField(
            model_name='sprintresult',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.status', verbose_name='Sprint Status'),
        ),
        migrations.CreateModel(
            name='SprintRace',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Sprint Race ID')),
                ('date', models.DateField(verbose_name='Sprint Date')),
                ('time', models.TimeField(blank=True, verbose_name='Sprint Time')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.race', verbose_name='Race Id')),
            ],
            options={
                'verbose_name_plural': 'Sprint Races',
            },
        ),
        migrations.CreateModel(
            name='SprintFastestLap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Sprint Fastest Lap ID')),
                ('lap', models.IntegerField(verbose_name='Sprint Lap')),
                ('time', models.TimeField(verbose_name='Sprint fastest lap time')),
                ('sprint_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.sprintresult', verbose_name='Sprint Result Id')),
            ],
            options={
                'verbose_name_plural': 'Sprint Fastest Laps',
            },
        ),
        migrations.CreateModel(
            name='ResultTime',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Time in milliseconds ID')),
                ('milliseconds', models.IntegerField(blank=True, null=True, verbose_name='Time in Milliseconds')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.result', verbose_name='Result ID')),
            ],
            options={
                'verbose_name_plural': 'Milliseconds',
            },
        ),
        migrations.AddField(
            model_name='result',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.status', verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='QualifySession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Qualify ID')),
                ('date', models.DateField(verbose_name='Qualify Date')),
                ('time', models.TimeField(blank=True, verbose_name='Qualify Time')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.race', verbose_name='Race Id')),
            ],
            options={
                'verbose_name_plural': 'Qualify Sessions',
            },
        ),
        migrations.CreateModel(
            name='Qualifying',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Qualifying ID')),
                ('number', models.IntegerField(verbose_name='Number driver')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.constructor', verbose_name='Construtor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.driver', verbose_name='Driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.race', verbose_name='Gran Prix')),
            ],
            options={
                'verbose_name_plural': 'Qualifyings',
            },
        ),
        migrations.CreateModel(
            name='Qualify_3',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Q3 ID')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Q3 Lap Time')),
                ('qualifying', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.qualifying', verbose_name='Qualifying ID')),
            ],
            options={
                'verbose_name_plural': 'Q3s',
            },
        ),
        migrations.CreateModel(
            name='Qualify_2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Q2 ID')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Q2 Lap Time')),
                ('qualifying', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.qualifying', verbose_name='Qualifying ID')),
            ],
            options={
                'verbose_name_plural': 'Q2s',
            },
        ),
        migrations.CreateModel(
            name='Qualify_1',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Q1 ID')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Q1 Lap Time')),
                ('qualifying', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.qualifying', verbose_name='Qualifying ID')),
            ],
            options={
                'verbose_name_plural': 'Q1s',
            },
        ),
        migrations.CreateModel(
            name='PitStop',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Pit Stop ID')),
                ('stop', models.IntegerField(verbose_name='Stop')),
                ('lap', models.IntegerField(verbose_name='Lap')),
                ('miles', models.IntegerField(verbose_name='Time in Miles')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.driver', verbose_name='Driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.race', verbose_name='Gran Prix')),
            ],
            options={
                'verbose_name_plural': 'Pit Stops',
            },
        ),
        migrations.CreateModel(
            name='LapTime',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Lap ID')),
                ('lap', models.IntegerField(verbose_name='Lap')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('mile_seconds', models.IntegerField(verbose_name='Time in Miles')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.driver', verbose_name='Driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.race', verbose_name='Gran Prix')),
            ],
            options={
                'verbose_name_plural': 'Lap Times',
            },
        ),
        migrations.CreateModel(
            name='FreePractice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Free Practice ID')),
                ('type', models.IntegerField(choices=[(1, 'FP1'), (2, 'FP2'), (3, 'FP3')], verbose_name='Type session')),
                ('date', models.DateField(verbose_name='Free Practice Date')),
                ('time', models.TimeField(blank=True, verbose_name='Free Practice Time')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.race')),
            ],
            options={
                'verbose_name_plural': 'Free Practices',
            },
        ),
        migrations.CreateModel(
            name='FastestLap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Fastest Lap ID')),
                ('lap', models.IntegerField(verbose_name='Lap')),
                ('rank', models.IntegerField(verbose_name='Rank Fastest Lap')),
                ('time', models.TimeField(verbose_name='Time Lap')),
                ('speed', models.FloatField(verbose_name='Speed lap')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.result', verbose_name='Result Id')),
            ],
            options={
                'verbose_name_plural': 'Fastest Laps',
            },
        ),
        migrations.CreateModel(
            name='DriverStanding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Driver Standing ID')),
                ('points', models.FloatField(verbose_name='Points')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('position_text', models.CharField(max_length=65, verbose_name='Position Txt')),
                ('wins', models.IntegerField(verbose_name='Wins')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.driver', verbose_name='Driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.race', verbose_name='Gran Prix')),
            ],
            options={
                'verbose_name_plural': 'Drivers Standings',
            },
        ),
        migrations.CreateModel(
            name='ConstructorStanding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Constructor Standing ID')),
                ('points', models.FloatField(verbose_name='Points')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('position_text', models.CharField(max_length=65, verbose_name='Position Txt')),
                ('wins', models.IntegerField(verbose_name='Wins')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.constructor', verbose_name='Constructor')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.race', verbose_name='Gran Prix')),
            ],
            options={
                'verbose_name_plural': 'Constructors Standings',
            },
        ),
        migrations.CreateModel(
            name='ConstructorResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Constructor Result ID')),
                ('points', models.FloatField(verbose_name='Points')),
                ('status', models.CharField(max_length=65, verbose_name='status')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.constructor', verbose_name='Construtor')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.race', verbose_name='Gran Prix')),
            ],
            options={
                'verbose_name_plural': 'Constructors Results',
            },
        ),
    ]
